### ISSUE TITLE
Enhance UI with Additional Features

### ISSUE THREAD

**Issue by kaybrian** [pycon-rwanda/Endangered-Species-Tracker#8]
Add options for users to filter species by conservation status (e.g., Vulnerable, Endangered, etc.) in the Gradio interface.

**Comment by roshankraveendrababu** [comment]
please assign me this issue . i will follow the code of conduct diligently and completely the task successfully. please consider my application for review.!!

**Comment by kaybrian** [comment]
i got some error when i tried to run the code, 

Traceback (most recent call last):
  File "/Users/bliss/Desktop/Open Source /Speice Tracker /env/lib/python3.12/site-packages/gradio/routes.py", line 534, in predict
    output = await route_utils.call_process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bliss/Desktop/Open Source /Speice Tracker /env/lib/python3.12/site-packages/gradio/route_utils.py", line 226, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bliss/Desktop/Open Source /Speice Tracker /env/lib/python3.12/site-packages/gradio/blocks.py", line 1559, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bliss/Desktop/Open Source /Speice Tracker /env/lib/python3.12/site-packages/gradio/blocks.py", line 1447, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bliss/Desktop/Open Source /Speice Tracker /env/lib/python3.12/site-packages/gradio/components/markdown.py", line 80, in postprocess
    unindented_y = inspect.cleandoc(y)
                   ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/inspect.py", line 888, in cleandoc
    lines = doc.expandtabs().split('\n')
            ^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'expandtabs'



can you look into it

**Comment by roshankraveendrababu** [comment]
should i make an new pull request with the small changes or list out the changes here for you to change them !!
